#!/bin/sh

sudo apt-get install build-essential zsh tmux \
		     nmap jq vim weechat git-flow \
		     silversearcher-ag

chsh -s /bin/zsh

# Install rbenv & ruby-build
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# Install nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
		     
./install_prezto
