#!/bin/sh

sudo apt-get install jq \
                     zsh \
		     nmap \
                     tmux \
                     weechat \
                     git-flow \
                     ruby-dev \
                     python-dev \
                     build-essential \
                     haskell-platform \
		     silversearcher-ag

chsh -s `which zsh`

# Install rbenv & ruby-build
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# Install nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
