#!/bin/sh

ln -sh ~/dotfiles/vim ~/.vim
ln -sh ~/dotfiles/emacs ~/.emacs.d
ln -sh ~/dotfiles/weechat ~/.weechat
ln -sh ~/dotfiles/zshrc ~/.zshrc
ln -sh ~/dotfiles/jshintrc ~/.jshintrc
ln -sh ~/dotfiles/tmux.conf ~/.tmux.conf
ln -sh ~/dotfiles/gitconfig ~/.gitconfig
# ln -sh ~/dotfiles/git_template ~/.git_template
ln -sh ~/dotfiles/gitignore_global ~/.gitignore_global
ln -sh ~/dotfiles/prompt_dhruva_setup ~/.zprezto/modules/prompt/functions/prompt_dhruva_setup
