#!/bin/sh

rm -rf ~/.vim ~/.nvim ~/.emacs.d ~/.weechat ~/.jshintrc ~/.tmux.conf \
       ~/.zshrc ~/.gitconfig ~/.gitignore_global \
       ~/.zprezto/modules/prompt/functions/prompt_dhruva_setup ~/.ssh/config

ln -s ~/dotfiles/vim ~/.vim
ln -s ~/dotfiles/vim ~/.nvim
ln -s ~/dotfiles/emacs ~/.emacs.d
ln -s ~/dotfiles/weechat ~/.weechat
ln -s ~/dotfiles/zshrc ~/.zshrc
ln -s ~/dotfiles/jshintrc ~/.jshintrc
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/gitconfig ~/.gitconfig
# ln -s ~/dotfiles/git_template ~/.git_template
ln -s ~/dotfiles/gitignore_global ~/.gitignore_global

mkdir -p ~/.ssh
ln -s ~/dotfiles/sshconfig ~/.ssh/config

platform=$(uname | awk '{print tolower($0)}')
if [ -f "install_$platform" ]; then
  . "./install_$platform"
fi

ln -s ~/dotfiles/prompt_dhruva_setup ~/.zprezto/modules/prompt/functions/prompt_dhruva_setup
