#!/bin/sh

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install hub
brew install zsh
chsh -s `which zsh`

brew install jq
brew install tmux
brew install rbenv
brew install weechat
brew install ruby-build
brew install rbenv-gem-rehash
brew install the_silver_searcher

brew install caskroom/cask/brew-cask
brew cask install skype
brew cask insatll dropbox
brew cask install spectacles
brew cask install google-chrome

./install_darwin_prezto
