#!/bin/bash

sudo apt-get install jq \
                     zsh \
                     nmap \
                     tmux \
                     weechat \
                     git-flow \
                     python-dev \
                     build-essential \
                     haskell-platform \
		     ripgrep

# Dependencies for VIM
sudo apt-get install libxt-dev \
                     libx11-dev \
                     libxpm-dev \
                     python-dev \
                     libncurses-dev

[[ ! $SHELL =~ "zsh" ]] && chsh -s `which zsh`

# Install rbenv & ruby-build
if [[ ! -d ~/.rbenv ]]; then
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

# Install nvm
if [[ ! -d ~/.nvm ]]; then
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
fi
