#!/bin/zsh

[[ -d ~/.zprezto ]] && exit

git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

rm -rf ~/.zprofile ~/.zpreztorc ~/.zprezto/modules/prompt/functions/prompt_pristine_setup
ln -s ~/dotfiles/zprofile ~/.zprofile
ln -s ~/dotfiles/zpreztorc ~/.zpreztorc
ln -s ~/dotfiles/prompt_pristine_setup ~/.zprezto/modules/prompt/functions/prompt_pristine_setup
