#!/bin/bash

brew install zsh
[[ ! $SHELL =~ "zsh" ]] && chsh -s "$(command -v zsh)"

brew install jq
brew install fzf
brew install gcc
brew install hub
brew install bash
brew install htop
brew install nmap
brew install tmux
brew install wget
brew install awscli
brew install ledger
brew install ripgrep
brew install weechat
brew install reattach-to-user-namespace

# gnu tools better than osx defaults
brew install gawk
brew install gnupg
brew install gnutls
brew install gnu-sed
brew install gnu-tar
brew install coreutils
brew install moreutils
brew install gnu-indent
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew install caskroom/cask/brew-cask
brew tap homebrew/cask-versions

brew cask install ngrok
brew cask install skype
brew cask install slack
brew cask install steam
brew cask install docker
brew cask install iterm2
brew cask install skitch
brew cask install dropbox
brew cask install keybase
brew cask install caffeine
brew cask install spectacle

brew tap homebrew/cask-fonts
brew cask install font-hack-nerd-font
brew cask install font-fira-nerd-font
brew cask install font-source-code-pro

brew cask install google-chrome
brew cask install firefox-developer-edition
