#!/bin/bash

rm -rf ~/.vim \
       ~/.nvim \
       ~/.mutt \
       ~/.zshrc \
       ~/.emacs.d \
       ~/.weechat \
       ~/.jshintrc \
       ~/.tmux.conf \
       ~/.gitconfig \
       ~/.ssh/config \
       ~/.tridactylrc \
       ~/.gitignore_global \
       ~/.gitcommit_template

ln -s ~/dotfiles/vim ~/.vim

mkdir -p "${XDG_CONFIG_HOME:=$HOME/.config}"
ln -s ~/dotfiles/vim "${XDG_CONFIG_HOME}/nvim"

ln -s ~/dotfiles/emacs ~/.emacs.d
ln -s ~/dotfiles/weechat ~/.weechat
ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/dotfiles/jshintrc ~/.jshintrc
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf

ln -s ~/dotfiles/gitconfig ~/.gitconfig
# ln -s ~/dotfiles/git_template ~/.git_template
ln -s ~/dotfiles/vim/tridactylrc ~/.tridactylrc
ln -s ~/dotfiles/gitcommit_template ~/.gitcommit_template
ln -s ~/dotfiles/gitignore_global ~/.gitignore_global

mkdir -p ~/.ssh
ln -s ~/dotfiles/sshconfig ~/.ssh/config

platform=$(uname | awk '{print tolower($0)}')
# shellcheck source=/dev/null
[[ -f "setup_$platform" ]] && source "./setup_$platform"

./setup_vim
./setup_asdf
