#!/bin/bash

relink () {
  src="$1"
  dst="$2"

  rm -rf "$dst"

  dir=$(dirname "$dst")
  [[ ! -d "$dir" ]] && mkdir -p "$dir"

  ln -s "$src" "$dst"
}

XDG_CONFIG_HOME=$XDG_CONFIG_HOME:=$HOME/.config

relink ~/dotfiles/vim ~/.vim
relink ~/dotfiles/emacs ~/.emacs.d
relink ~/dotfiles/weechat ~/.weechat
relink ~/dotfiles/zsh/zshrc ~/.zshrc
relink ~/dotfiles/tmux.conf ~/.tmux.conf
relink ~/dotfiles/qutebrowser ~/.qutebrowser
relink ~/dotfiles/vim/tridactylrc ~/.tridactylrc
relink ~/dotfiles/sshconfig ~/.ssh/config
relink ~/dotfiles/xprofile ~/.xprofile

relink ~/dotfiles/i3 "${XDG_CONFIG_HOME}/i3"
relink ~/dotfiles/vim "${XDG_CONFIG_HOME}/nvim"
relink ~/dotfiles/alacritty.yml "${XDG_CONFIG_HOME}/alacritty/alacritty.yml"

platform=$(uname | awk '{print tolower($0)}')
# shellcheck source=/dev/null
[[ -f "setup_$platform" ]] && source "./setup_$platform"

./setup_git
./setup_vim
./setup_tmux
./setup_asdf
./setup_pass
