#!/bin/bash

# relink ~/dotfiles/config/skhdrc "${XDG_CONFIG_HOME}/skhd/skhdrc"
# relink ~/dotfiles/config/yabairc ~/.yabairc
relink ~/dotfiles/hammerspoon ~/.hammerspoon
relink ~/dotfiles/config/aerospace.toml ~/.aerospace.toml
# relink ~/dotfiles/config/spacebarrc "${XDG_CONFIG_HOME}/spacebar/spacebarrc"

brew install zsh
[[ ! $SHELL =~ "zsh" ]] && chsh -s "$(command -v zsh)"

brew install jq
brew install bat
brew install fzf
brew install gcc
brew install hub
brew install bash
brew install htop
brew install nmap
brew install tmux
brew install wget
brew install awscli
brew install neovim
brew install ledger
brew install ripgrep
brew install weechat
brew install reattach-to-user-namespace

# brew install koekeishiya/formulae/skhd
# brew install koekeishiya/formulae/yabai

# gnu tools better than osx defaults
brew install gawk
brew install gnupg
brew install gnutls
brew install colima
brew install gnu-sed
brew install gnu-tar
brew install coreutils
brew install moreutils
brew install gnu-indent
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew tap homebrew/cask
brew tap homebrew/cask-versions

brew install --cask kap
brew install --cask pika
brew install --cask ngrok
brew install --cask skype
brew install --cask slack
brew install --cask steam
brew install --cask skitch
brew install --cask dropbox
brew install --cask keybase
brew install --cask wezterm
brew install --cask caffeine
brew install --cask alacritty
# brew install --cask rectangle
brew install --cask hammerspoon
brew install --cask nikitabobko/tap/aerospace

brew tap homebrew/cask-fonts
brew install --cask font-fira-sans # for Italics
brew install --cask font-fira-code-nerd-font

brew install --cask firefox
brew install --cask qutebrowser
