#!/bin/bash

# Install asdf
if [[ ! -d ~/.asdf ]]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  source ~/.asdf/asdf.sh

  asdf plugin-add ruby
  asdf plugin-add golang
  asdf plugin-add haskell
  asdf plugin-add python
fi
