#!/bin/bash

sudo apt-get install jq \
                     fzf \
                     zsh \
                     htop \
                     nmap \
                     tmux \
                     awscli \
                     ripgrep \
                     weechat \
                     git-flow \
                     caffeine \
                     docker.io \
                     build-essential

if [ $+commands[snap] ]; then
  sudo snap install ngrok

  snap install hub --classic
  sudo snap install slack --classic
  sudo snap install skype --classic
  sudo snap install keybase --edge
fi

# Install dependencies for VIM
sudo apt-get install libxt-dev \
                     libx11-dev \
                     libxpm-dev \
                     python-dev \
                     python3-dev \
                     libncurses-dev

# Install dependencies for TMUX
sudo apt install -y automake \
                    bison \
                    pkg-config \
                    libevent-dev \
                    libncurses5-dev

[[ ! $SHELL =~ "zsh" ]] && chsh -s `which zsh`
