#!/bin/bash

brew install zsh
[[ ! $SHELL =~ "zsh" ]] && chsh -s `which zsh`

brew install jq
brew install nvm
brew install nmap
brew install tmux
brew install lynx
brew install pandoc
brew install ripgrep
brew install weechat
brew install leiningen
brew install reattach-to-user-namespace

# gnu tools better than osx defaults
brew install gawk --with-default-names
brew install gnutls --with-default-names
brew install gnu-sed --with-default-names
brew install gnu-tar --with-default-names
brew install coreutils --with-default-names
brew install gnu-indent --with-default-names

brew install caskroom/cask/brew-cask
brew cask install ngrok
brew cask install skype
brew cask install docker
brew cask install iterm2
brew cask install skitch
brew cask install typora
brew cask install dropbox
brew cask install spectacle
brew cask install google-chrome
brew cask install karabiner-elements
