#!/bin/bash

sudo apt-get install jq \
                     fzf \
                     zsh \
                     nmap \
                     tmux \
                     ripgrep \
                     weechat \
                     git-flow \
                     build-essential

# Dependencies for VIM
sudo apt-get install libxt-dev \
                     libx11-dev \
                     libxpm-dev \
                     python-dev \
                     libncurses-dev

[[ ! $SHELL =~ "zsh" ]] && chsh -s `which zsh`
