#!/bin/bash

relink ~/dotfiles/git/config ~/.gitconfig
relink ~/dotfiles/git/ignore ~/.gitignore
# relink ~/dotfiles/git/template ~/.git_template
relink ~/dotfiles/git/attributes ~/.gitattributes
relink ~/dotfiles/git/commit_template ~/.gitcommittemplate
