#!/bin/bash

# Clone & build tmux
if [[ ! -d ~/src/oss/tmux ]]; then
    git clone git@github.com:tmux/tmux.git ~/src/oss/tmux
    cd ~/src/oss/tmux

    # Compile & Install Tmux
    sh autogen.sh
    ./configure --enable-utf8proc && make
    sudo make install
fi
