#!/bin/bash

# Clone & buildvim
if [[ ! -d ~/src/oss/vim ]]; then
  git clone git@github.com:vim/vim.git ~/src/oss/vim
  cd ~/src/oss/vim
  ~/dotfiles/bin/buildvim

  # Install Packup
  git clone git@github.com:dhruvasagar/packup.git ~/.vim/pack/packup/opt/packup

  vim +PackupInstall +qall
fi
