#!/bin/bash

rm -rf ~/.vim \
       ~/.nvim \
       ~/.mutt \
       ~/.zshrc \
       ~/.emacs.d \
       ~/.weechat \
       ~/.tmux.conf \
       ~/.gitconfig \
       ~/.ssh/config \
       ~/.tridactylrc \
       ~/.hammerspoon \
       ~/.qutebrowser \
       ~/.gitignore_global \
       ~/.gitcommit_template

ln -s ~/dotfiles/vim ~/.vim

XDG_CONFIG_HOME=$XDG_CONFIG_HOME:=$HOME/.config
rm -rf "${XDG_CONFIG_HOME}/nvim"
mkdir -p "${XDG_CONFIG_HOME}"
ln -s ~/dotfiles/vim "${XDG_CONFIG_HOME}/nvim"

ln -s ~/dotfiles/emacs ~/.emacs.d
ln -s ~/dotfiles/weechat ~/.weechat
ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/hammerspoon ~/.hammerspoon
ln -s ~/dotfiles/qutebrowser ~/.qutebrowser
# ln -s ~/dotfiles/git_template ~/.git_template
ln -s ~/dotfiles/vim/tridactylrc ~/.tridactylrc
ln -s ~/dotfiles/gitignore_global ~/.gitignore_global
ln -s ~/dotfiles/gitcommit_template ~/.gitcommit_template

rm -rf ~/.config/alacritty
mkdir -p ~/.config/alacritty
ln -s ~/dotfiles/alacritty.yml ~/.config/alacritty/alacritty.yml

mkdir -p ~/.ssh
ln -s ~/dotfiles/sshconfig ~/.ssh/config

platform=$(uname | awk '{print tolower($0)}')
# shellcheck source=/dev/null
[[ -f "setup_$platform" ]] && source "./setup_$platform"

./setup_vim
./setup_asdf
