return {
  "tpope/vim-rsi",
  "tpope/vim-rake",
  "tpope/vim-tbone",
  "tpope/vim-apathy",
  "tpope/vim-repeat",
  "tpope/vim-abolish",
  "tpope/vim-endwise",
  "tpope/vim-rhubarb",
  {
    "tpope/vim-dispatch",
    lazy = true,
    cmd = { "Dispatch", "Make", "Focus", "Start" },
  },
  "tpope/vim-fugitive",
  "tpope/vim-sensible",
  { "tpope/vim-fireplace", lazy = true },
  { "tpope/vim-leiningen", lazy = true },
  -- "tpope/vim-commentary",
  "tpope/vim-scriptease",
  "tpope/vim-unimpaired",
  "tpope/vim-speeddating",
  "tpope/vim-characterize",
  { "tpope/vim-sexp-mappings-for-regular-people", lazy = true },
  "tpope/vim-rails",
  "tpope/vim-eunuch",
  "tpope/vim-bundler",
  "tpope/vim-cucumber",
}
