" NoCompatible {{{1
set nocp

" NeoBundle {{{1
source ~/.vim/neo_bundles.vim

" Load all vim configs {{{1
let s:vim_home = '~/.vim/'
let config_list = [
      \ 'config.vim',
      \ 'autocmd.vim',
      \ 'commands.vim',
      \ 'mappings.vim',
      \ 'plugin_settings/*.vim'
      \]
for files in config_list
  for f in split(glob(s:vim_home.files), '\n')
    exec 'source ' . f
  endfor
endfor

" Set at the end to work around 'exrc'
set secure
