" NoCompatible {{{1
set nocp

" NeoBundle {{{1
source ~/.vim/neo_bundles.vim

" Powerline {{{1
set runtimepath+=/home/dhruvasagar/code/powerline/powerline/bindings/vim

" Auto Command Groups {{{1
augroup vimrcEx "{{{2
  au!

  " Automatically load .vimrc changes
  autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END

augroup NeoBundles "{{{2
  au!

  autocmd BufWritePost neo_bundles.vim source $MYVIMRC
augroup END

augroup EditJump "{{{2
  au!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  autocmd BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \   exe "normal g`\"" |
        \ endif
augroup END

" Load all vim configs {{{1
let s:vim_home = '~/.vim/'
let config_list = [
      \ 'base.vim',
      \ 'functions.vim',
      \ 'mappings.vim',
      \ 'plugin_settings/*.vim'
      \]
for files in config_list
  for f in split(glob(s:vim_home.files), '\n')
    exec 'source ' . f
  endfor
endfor

" Set at the end to work around 'exrc'
set secure
