(require 'util)
(require 'init-straight)
(require 'init-general)
(require 'init-org)
(require 'init-evil)
(require 'init-consult)
(require 'init-packages)
(require 'init-embark)
(require 'init-themes)
(require 'ui)
(require 'init-lsp)
(require 'init-langs)
(when (locate-library "mu4e")
  (require 'init-mu4e))
(require 'init-erc)
(require 'init-ai)
(require 'aoc-mode)
;; (require 'eaf)
(require 'send-to-buffer)

(provide 'ds)
