# zmodload zsh/zprof

stty -ixon

bindkey -e

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

export EDITOR='vim'
export VISUAL='vim'

# Setup PATH
PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
PATH=/usr/local/bin:/usr/local/sbin:$PATH
PATH=$HOME/dotfiles/bin:$PATH
PATH=$HOME/bin:$PATH
export PATH
MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH
export MANPATH

# Setup CDPATH for directory completion
. ~/dotfiles/zsh/cdpath

# Setup Prompt
. ~/dotfiles/zsh/pristine_prompt

# Setup functions
. ~/dotfiles/zsh/funcs

# Setup aliases
. ~/dotfiles/zsh/aliases

# TERM with at least 256 colors (24 bit on supported terminals)
export TERM=xterm-256color

# Add cabal bins to PATH
if [[ -d ~/.cabal/bin ]]; then
  export PATH=$HOME/.cabal/bin:$PATH
fi

# cassandra
if [[ -d "$HOME/cassandra" ]]; then
  export CASSANDRA_HOME=~/cassandra
  export PATH=$CASSANDRA_HOME/bin:$PATH
fi

# go lang
if [ $+commands[go] ]; then
  export GOPATH=$HOME/code/go
  export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
fi

platform=$(uname | awk '{print tolower($0)}')
if [[ "$platform" == "darwin" ]]; then
  export ANDROID_NDK_HOME="/usr/local/share/android-ndk"
  export ANDROID_SDK_HOME="/usr/local/share/android-sdk"
fi

# Commented because very slow
# if [ $+commands[kubectl] ]; then
#   source <(kubectl completion zsh)
# fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/path.zsh.inc' ]; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/completion.zsh.inc' ]; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/completion.zsh.inc'
fi

if [[ -d "$HOME/.asdf" ]]; then
  . "$HOME/.asdf/asdf.sh"
  # completions require compdef which slows zsh a bit
  # . "$HOME/.asdf/completions/asdf.bash"
fi

# zprof
